[package]
name = "extism-runtime"
version = "0.0.1-rc.6"
edition = "2021"
authors = ["The Extism Authors", "oss@extism.org"]
license = "BSD-3-Clause"
homepage = "https://extism.org"
repository = "https://github.com/extism/extism"
description = "Extism runtime component"

[lib]
name = "extism"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "2.0.1"
wasmtime-wasi = "2.0.1"
wasmtime-wasi-nn = {version = "2.0.1", optional=true}
anyhow = "1"
serde = { version = "1", features=["derive"] }
toml = "0.5"
serde_json = "1"
sha2 = "0.10"
log = "0.4"
log4rs = "1.1"
url = "2.3"
glob = "0.3"
ureq = {version = "2.5", optional=true}
extism-manifest = { version = "0.0.1-rc.6", path = "../manifest" }
pretty-hex = { version = "0.3" }

[features]
default = ["http", "register-http", "register-filesystem"]
nn = ["wasmtime-wasi-nn"]
register-http = ["ureq"] # enables wasm to be downloaded using http
register-filesystem = [] # enables wasm to be loaded from disk
http = ["ureq"]          # enables extism_http_request

[build-dependencies]
cbindgen = "0.24"
