[package]
name = "extism-runtime"
version = "0.0.1-rc.3"
edition = "2021"
authors = ["The Extism Authors", "oss@extism.org"]
license = "BSD-3-Clause"
homepage = "https://extism.org"
repository = "https://github.com/extism/extism"
description = "Extism runtime component"

[lib]
name = "extism"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.40.0"
wasmtime-wasi = "0.40.0"
anyhow = "1"
serde = { version = "1", features=["derive"] }
toml = "0.5"
serde_json = "1"
sha2 = "0.10"
log = "0.4"
log4rs = "1.1"
ureq = {version = "2.5", optional=true}
extism-manifest = { version = "0.0.1-rc.3", path = "../manifest" }
pretty-hex = { version = "0.3" }

[features]
default = ["http", "register-http", "register-filesystem"]
register-http = ["ureq"] # enables wasm to be downloaded using http
register-filesystem = [] # enables wasm to be loaded from disk
http = ["ureq"]          # enables extism_http_request

[build-dependencies]
cbindgen = "0.24"
