[package]
name = "extism-runtime-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
wasm-bindgen-test = "0.3.39"

[features]
default = ["bounds-checking"]
bounds-checking = []

[workspace]
members = [
  "."
]